const recruitmentData = [
  {
    "sno": 1,
    "name": "Kavitha Perumal",
    "function": "Clinical Data",
    "role": "Clinical Programmer",
    "interviewDate": "14th July",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 2,
    "name": "Himabindu Gunikuntla",
    "function": "Clinical Data",
    "role": "External Data Manager",
    "interviewDate": "14th July",
    "interview2": "Completed",
    "clientFeedback": "Offer shortlisted",
    "presentCtcRaw": "INR 9,80,000",
    "status": "Offered",
    "offeredCtcRaw": "1250000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 3,
    "name": "Trayambica Acharya",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "15th July",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 4,
    "name": "Kavya Shree R",
    "function": "Clinical Data",
    "role": "Clinical Programmer",
    "interviewDate": "14th July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 7,50,000",
    "status": "Offered",
    "offeredCtcRaw": "1320000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 5,
    "name": "Sai kumar mahidar",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "16th July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 6,50,000",
    "status": "Offered",
    "offeredCtcRaw": "770000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 6,
    "name": "Karan Marathe",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "14th July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 8,00,000",
    "status": "Offered",
    "offeredCtcRaw": "1050000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 7,
    "name": "Rohini Singamaneni",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "15th July",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 8,
    "name": "K Sangeeta",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "14th July",
    "interview2": "",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 5,30,000",
    "status": "Offered",
    "offeredCtcRaw": "770000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 9,
    "name": "Hemavantha patil",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "16th July",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 10,
    "name": "Shivani Attri",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "16th July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 11,50,000",
    "status": "Offered",
    "offeredCtcRaw": "1250000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 11,
    "name": "Bharath kumar",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "16th July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 9,00,000",
    "status": "Offered",
    "offeredCtcRaw": "1320000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 12,
    "name": "Sudipta Chakraborty",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "15th July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 16,90,000",
    "status": "Offered",
    "offeredCtcRaw": "1850000",
    "doj": "03-08-2026",
    "onboard": "Onboarded",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 13,
    "name": "Madan kumar",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "15TH JULY",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 14,
    "name": "Pavithra",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "20th July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offered",
    "offeredCtcRaw": "770000",
    "doj": "01-11-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 15,
    "name": "Kiranmai",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "20th July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "850000",
    "status": "Offered",
    "offeredCtcRaw": "1000000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 16,
    "name": "Omkar",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "20th July",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 17,
    "name": "shiwangi",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "20th July",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 18,
    "name": "Ritu Jois",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "21st July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 8,30,000",
    "status": "Offered",
    "offeredCtcRaw": "924000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 19,
    "name": "Abhishek Suresh Vishwasrao",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "19th July",
    "interview2": "",
    "clientFeedback": "Int No Show",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 20,
    "name": "Nidhi Nayan",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 21,
    "name": "Sk samdhani",
    "function": "Clinical Data",
    "role": "External Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 22,
    "name": "Lavanya Guntur",
    "function": "Clinical Data",
    "role": "External Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 23,
    "name": "Rajeswari",
    "function": "Clinical Data",
    "role": "Clinical Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 24,
    "name": "Kavitha Perumal",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "22nd July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offered",
    "offeredCtcRaw": "1450000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 25,
    "name": "Anvith Ullal",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "22nd July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 26,
    "name": "Archana kothireddy",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "22nd July",
    "interview2": "Completed",
    "clientFeedback": "Candidate Drop",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 27,
    "name": "Sridevi Huli",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "22nd July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offered",
    "offeredCtcRaw": "820000",
    "doj": "01-10-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 28,
    "name": "Dr. Yagni Patel",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "23rd July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offered",
    "offeredCtcRaw": "780000",
    "doj": "01-11-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 29,
    "name": "Vrushabh Kondalkar",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "23rd July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offered",
    "offeredCtcRaw": "780000",
    "doj": "01-11-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 30,
    "name": "Sompalli Padmavathi",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "23rd July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offered",
    "offeredCtcRaw": "780000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 31,
    "name": "Dr. Aniket Somnath Deore",
    "function": "Clinical Data",
    "role": "Medical Coder",
    "interviewDate": "24TH JULY",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 32,
    "name": "Dr. Jamuna Konapalli",
    "function": "Clinical Data",
    "role": "Medical Coder",
    "interviewDate": "23rd July",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offered",
    "offeredCtcRaw": "1200000",
    "doj": "01-11-2026",
    "onboard": "YTO",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 33,
    "name": "Jitendra Chauhan",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "27th July",
    "interview2": "Completed",
    "clientFeedback": "Offer shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 34,
    "name": "Meghana",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "28th July",
    "interview2": "Completed",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 35,
    "name": "Premsai",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "27th July",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 36,
    "name": "Ankit Goyal",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "24th July",
    "interview2": "",
    "clientFeedback": "Drop",
    "presentCtcRaw": "",
    "status": "Candidate No Show",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 37,
    "name": "Sirisha GA",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "28th July",
    "interview2": "Completed",
    "clientFeedback": "Offer shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 38,
    "name": "Ranjeeta Sinha",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "30th March",
    "interview2": "Completed",
    "clientFeedback": "Offer shortlisted",
    "presentCtcRaw": "INR 10,00,000",
    "status": "Offered",
    "offeredCtcRaw": "1250000",
    "doj": "03-08-2026",
    "onboard": "Onboarded",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 39,
    "name": "Sita Ratnam Nunna",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "30th March",
    "interview2": "Completed",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 40,
    "name": "Shubhangi Kale",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "2nd April",
    "interview2": "Completed",
    "clientFeedback": "Offer shortlisted",
    "presentCtcRaw": "INR 21,00,000",
    "status": "Offered",
    "offeredCtcRaw": "2280000",
    "doj": "03-08-2026",
    "onboard": "Onboarded",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 41,
    "name": "Arpit Chitransh",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "30th March",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Candidate No Show",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 42,
    "name": "Sathish Kumar H",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "30th March",
    "interview2": "Completed",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 43,
    "name": "Dr. Kumar Mahesh",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "2nd April",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 31,00,000",
    "status": "Offered",
    "offeredCtcRaw": "2700000",
    "doj": "03-08-2026",
    "onboard": "Onboarded",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 44,
    "name": "Saurav Sinha",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "9th April",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 45,
    "name": "Katam Veera Nagendra",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "9th April",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 46,
    "name": "Agalya Rajendran",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "9th April",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 47,
    "name": "Chakali Gowtham Kumar",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "31st March",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 48,
    "name": "Ansar Shaik",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 49,
    "name": "Satish Halappanavar",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 50,
    "name": "Anusha B Bhaskar",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 51,
    "name": "Vinay Kumar",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 52,
    "name": "Akshay Sanjay Karne",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 53,
    "name": "Manikannan Kannusamy",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 54,
    "name": "Vasuki Natarajan",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 55,
    "name": "Saiki Volvoikar",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 56,
    "name": "Rajashekar Hachadad",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 57,
    "name": "Rohit Bhandarakavate",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 59,
    "name": "Avinash Belure",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 60,
    "name": "Parmeshwar Madke,",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 61,
    "name": "Usha",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 62,
    "name": "Gayatri Gireesh,",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 63,
    "name": "Chaitail Khandelwal",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 64,
    "name": "Dr Aayesha",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 65,
    "name": "Minal Mangesh Jadhav",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 66,
    "name": "Pravin",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 67,
    "name": "Abhilash Varma",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": "RAVE Programmer"
  },
  {
    "sno": 68,
    "name": "Siddhesh Chalke",
    "function": "Clinical Data",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": "RAVE Programmer"
  },
  {
    "sno": 69,
    "name": "Ansari Aishabanu,",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 70,
    "name": "Aakansha Murekar,",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 71,
    "name": "HARSHADA KHANDGE",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 72,
    "name": "Shahin Jawle,",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 73,
    "name": "Nikita Awate,",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 74,
    "name": "Avinash Urhekar",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 75,
    "name": "Vijay Halde",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 76,
    "name": "Greeshma Jadhav,",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 77,
    "name": "Jenish Evana Nvss",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 78,
    "name": "Medara Akhil Babu",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 79,
    "name": "Shravani Somayajula",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 80,
    "name": "Lavanya Krishna",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 81,
    "name": "Lavanya Gunda",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 82,
    "name": "Vijitha Kumar",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 83,
    "name": "Devyani Supe",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 84,
    "name": "Anila Balan B",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 85,
    "name": "Diksha Khandale",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 86,
    "name": "Prajesh Patil",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 87,
    "name": "Naga Vamsi,",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 88,
    "name": "Arunachaleswari Panneerselvam",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 89,
    "name": "Alka Devvanshi,",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 90,
    "name": "Prajakta Kashalikar,",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 91,
    "name": "M Rangaswamy,",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 92,
    "name": "Sauradeep Mitra,",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 93,
    "name": "Jay Bhalerao",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 94,
    "name": "Nupur Shimpi,",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 95,
    "name": "SHWETHA H",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 96,
    "name": "Heena Kausar",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 97,
    "name": "Jigyansha Sandha",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 98,
    "name": "Meher Taj",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 99,
    "name": "Swetha Somalaraju",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 100,
    "name": "Yashwanth D",
    "function": "Clinical Data",
    "role": "External Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 101,
    "name": "Pranjali Patil",
    "function": "Clinical Data",
    "role": "External Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 102,
    "name": "Rishil Shah,",
    "function": "Clinical Data",
    "role": "External Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 103,
    "name": "Shweta Shinde",
    "function": "Clinical Data",
    "role": "External Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 104,
    "name": "Sushmita Malik",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 105,
    "name": "Megha Shasrei,",
    "function": "Clinical Data",
    "role": "External Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 106,
    "name": "Nikesh kumar",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 107,
    "name": "Shraddha Mandale",
    "function": "Clinical Data",
    "role": "UAT Tester",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 108,
    "name": "Harini D",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 109,
    "name": "Sadaf Faizan",
    "function": "Clinical Data",
    "role": "External Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 110,
    "name": "karthik jain",
    "function": "Clinical Data",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 111,
    "name": "Hemanth jadhav",
    "function": "Clinical Data",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 112,
    "name": "Aditya Grada",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 113,
    "name": "Harish",
    "function": "Clinical Data",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 114,
    "name": "Yadavalli Santhosh Krishna Chaitanya",
    "function": "Clinical Data",
    "role": "External Data Manager",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 115,
    "name": "Rashimi K J",
    "function": "Clinical Data",
    "role": "External Data Manager",
    "interviewDate": "07-08-2026",
    "interview2": "",
    "clientFeedback": "Waiting for feedback",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Clinical Data",
    "roleSelected": ""
  },
  {
    "sno": 116,
    "name": "Naresh Kumar",
    "function": "Clinical Data",
    "role": "Report Programmer",
    "interviewDate": "04-08-2026",
    "interview2": "",
    "clientFeedback": "Waiting for feedback",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 117,
    "name": "Shai Lakshmi",
    "function": "Clinical Data",
    "role": "Report Programmer",
    "interviewDate": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 118,
    "name": "Himanshu Kumar Singh V",
    "function": "Clinical Data",
    "role": "Report Programmer",
    "interviewDate": "04-08-2026",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 119,
    "name": "Shayeestha Sheik",
    "function": "Clinical Data",
    "role": "Report Programmer",
    "interviewDate": "12-08-2026",
    "interview2": "",
    "clientFeedback": "Scheduled",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 120,
    "name": "Sandeep Gonela",
    "function": "Clinical Data",
    "role": "Report Programmer",
    "interviewDate": "11-08-2026",
    "interview2": "",
    "clientFeedback": "Waiting for feedback",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 121,
    "name": "Pranaya Pandharinath",
    "function": "Clinical Data",
    "role": "Report Programmer",
    "interviewDate": "11-08-2026",
    "interview2": "",
    "clientFeedback": "Waiting for feedback",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 122,
    "name": "Nourin Fakruddin Mullannava",
    "function": "Clinical Data",
    "role": "Report Programmer",
    "interviewDate": "11-08-2026",
    "interview2": "",
    "clientFeedback": "Waiting for feedback",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 123,
    "name": "Ameer Basha Valluri",
    "function": "Clinical Data",
    "role": "Report Programmer",
    "interviewDate": "07-08-2026",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  }
];

if (typeof module !== 'undefined') module.exports = recruitmentData;
