const recruitmentData = [
  {
    "sno": 1,
    "name": "Chandini K Jain",
    "function": "CDM",
    "role": "Clinical Programmer",
    "interviewDate": "14th July",
    "interviewStart": "11:30 AM",
    "interviewEnd": "12:00 PM",
    "contact": "7975391464",
    "email": "chandanikjain0904@gmail.com",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 2,
    "name": "Himabindu Gunikuntla",
    "function": "CDM",
    "role": "External Data Manager",
    "interviewDate": "14th July",
    "interviewStart": "3:30 PM",
    "interviewEnd": "4:00 PM",
    "contact": "7093398003",
    "email": "bindu.g30@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer shortlisted",
    "presentCtcRaw": "INR 9,80,000",
    "status": "Offered",
    "offeredCtcRaw": "1250000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 3,
    "name": "Trayambica Acharya",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "15th July",
    "interviewStart": "12:00 PM",
    "interviewEnd": "12:30 PM",
    "contact": "8374815833",
    "email": "acharyatrayambika@gmail.com",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 4,
    "name": "Kavya Shree R",
    "function": "CDM",
    "role": "Clinical Programmer",
    "interviewDate": "14th July",
    "interviewStart": "2:30 PM",
    "interviewEnd": "3:00 PM",
    "contact": "7349472379",
    "email": "kavyashree1261991@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 7,50,000",
    "status": "Offered",
    "offeredCtcRaw": "1320000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 5,
    "name": "Sai kumar mahidar",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "16th July",
    "interviewStart": "11:00 AM",
    "interviewEnd": "11:30 AM",
    "contact": "9154629109",
    "email": "mahidhar.nunna@outlook.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 6,50,000",
    "status": "Offered",
    "offeredCtcRaw": "770000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 6,
    "name": "Karan Marathe",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "14th July",
    "interviewStart": "1:00 PM",
    "interviewEnd": "1:30 PM",
    "contact": "9503438168",
    "email": "marathek776@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 8,00,000",
    "status": "Offered",
    "offeredCtcRaw": "1050000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 7,
    "name": "Rohini Singamaneni",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "15th July",
    "interviewStart": "11:00 AM",
    "interviewEnd": "11:30 AM",
    "contact": "8328238974",
    "email": "rohinisingamaneni@gmail.com",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 8,
    "name": "K Sangeeta",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "14th July",
    "interviewStart": "12:00 PM",
    "interviewEnd": "12:30 PM",
    "contact": "9742567651",
    "email": "sankeerthana7890@gmail.com",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 5,30,000",
    "status": "Offered",
    "offeredCtcRaw": "770000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 9,
    "name": "Hemavantha patil",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "16th July",
    "interviewStart": "3:00 PM",
    "interviewEnd": "3:30 PM",
    "contact": "9137012336",
    "email": "patilhemvanta123@gmail.com",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 10,
    "name": "Shivani Attri",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "16th July",
    "interviewStart": "1:30 PM",
    "interviewEnd": "2:00 PM",
    "contact": "9591706416",
    "email": "shivani.attri16@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 11,50,000",
    "status": "Offered",
    "offeredCtcRaw": "1250000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 11,
    "name": "Bharath kumar",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "16th July",
    "interviewStart": "12:30 PM",
    "interviewEnd": "1:00 PM",
    "contact": "8247673313",
    "email": "bharathkumar04b@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 9,00,000",
    "status": "Offered",
    "offeredCtcRaw": "1320000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 12,
    "name": "Sudipta Chakraborty",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "15th July",
    "interviewStart": "2:30 PM",
    "interviewEnd": "3:00 PM",
    "contact": "7829894158",
    "email": "mailtoschakraborty@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 16,90,000",
    "status": "Offered",
    "offeredCtcRaw": "1850000",
    "doj": "03-08-2026",
    "onboard": "Onboarded",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 13,
    "name": "Madan kumar",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "15TH JULY",
    "interviewStart": "12:30 PM",
    "interviewEnd": "1:00 PM",
    "contact": "8754217495",
    "email": "madan10nkl@gmail.com",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 14,
    "name": "Pavithra",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "20th July",
    "interviewStart": "12:30 PM",
    "interviewEnd": "1:00 PM",
    "contact": "7829643412",
    "email": "npavi36@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 15,
    "name": "Kiranmai",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "20th July",
    "interviewStart": "1:00 PM",
    "interviewEnd": "1:30 PM",
    "contact": "7382972143",
    "email": "jujjurikiranmai@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "850000",
    "status": "Offered",
    "offeredCtcRaw": "1000000",
    "doj": "01-09-2026",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 16,
    "name": "Omkar",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "20th July",
    "interviewStart": "4:30 PM",
    "interviewEnd": "5:00 PM",
    "contact": "7776985318",
    "email": "omkaryende@gmail.com",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 17,
    "name": "shiwangi",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "20th July",
    "interviewStart": "2:00 PM",
    "interviewEnd": "2:30 PM",
    "contact": "8840819948",
    "email": "Anandshiwangi0@gmail.com",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 18,
    "name": "Ritu Jois",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "21st July",
    "interviewStart": "12:30 PM",
    "interviewEnd": "1:00 PM",
    "contact": "9742849257",
    "email": "rithujois@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 8,30,000",
    "status": "Offered",
    "offeredCtcRaw": "924000",
    "doj": "01-09-2026",
    "onboard": "YTO",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 19,
    "name": "Abhishek Suresh Vishwasrao",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "19th July",
    "interviewStart": "3:00 PM",
    "interviewEnd": "3:30 PM",
    "contact": "9767465216",
    "email": "abhishekvishwasrao1@gmail.com",
    "interview1": "Candidate No Show",
    "interview2": "",
    "clientFeedback": "Int No Show",
    "presentCtcRaw": "",
    "status": "Int No Show",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 20,
    "name": "Nidhi Nayan",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9742786062",
    "email": "nidhinayan3@gmail.com",
    "interview1": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 21,
    "name": "Sk samdhani",
    "function": "CDM",
    "role": "External Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9901160443",
    "email": "samdhani.smart@gmail.com",
    "interview1": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 22,
    "name": "Lavanya Guntur",
    "function": "CDM",
    "role": "External Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9666377319/8466895178",
    "email": "lavanyamightyj7@gmail.com",
    "interview1": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 23,
    "name": "Rajeswari",
    "function": "CDM",
    "role": "Clinical Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9493956485",
    "email": "raajeswari.ca@gmail.com",
    "interview1": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 24,
    "name": "Kavitha Perumal",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "22nd July",
    "interviewStart": "12:30 PM",
    "interviewEnd": "1:00 PM",
    "contact": "9739576600",
    "email": "careers.kavi@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 25,
    "name": "Anvith Ullal",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "22nd July",
    "interviewStart": "3:30 PM",
    "interviewEnd": "4:00 PM",
    "contact": "9739127445",
    "email": "anvith.553@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 26,
    "name": "Archana kothireddy",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "22nd July",
    "interviewStart": "2:30 PM",
    "interviewEnd": "3:00 PM",
    "contact": "9676429911",
    "email": "archanareddy2025@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Candidate Drop",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 27,
    "name": "Sridevi Huli",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "22nd July",
    "interviewStart": "1:30 PM",
    "interviewEnd": "2:00 PM",
    "contact": "9916134368",
    "email": "rpk.sridevi@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 28,
    "name": "Dr. Yagni Patel",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "23rd July",
    "interviewStart": "3:30 PM",
    "interviewEnd": "4:00 PM",
    "contact": "9925221064",
    "email": "yagni.patel.96@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 29,
    "name": "Vrushabh Kondalkar",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "23rd July",
    "interviewStart": "1:30 PM",
    "interviewEnd": "2:00 PM",
    "contact": "9096057176",
    "email": "vrushabhkondalkar6@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 30,
    "name": "Sompalli Padmavathi",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "23rd July",
    "interviewStart": "12:30 PM",
    "interviewEnd": "1:00 PM",
    "contact": "7337656002",
    "email": "sompallipadma3@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 31,
    "name": "Dr. Aniket Somnath Deore",
    "function": "CDM",
    "role": "Medical Coder",
    "interviewDate": "24TH JULY",
    "interviewStart": "11:30 AM",
    "interviewEnd": "12:00 PM",
    "contact": "9167734492/8369241408",
    "email": "draniketd@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 32,
    "name": "Dr. Jamuna Konapalli",
    "function": "CDM",
    "role": "Medical Coder",
    "interviewDate": "23rd July",
    "interviewStart": "4:30 PM",
    "interviewEnd": "5:00 PM",
    "contact": "9110586698/9949333693",
    "email": "jamunareddyk8@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 33,
    "name": "Jitendra Chauhan",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "27th July",
    "interviewStart": "3:00 PM",
    "interviewEnd": "3:30 PM",
    "contact": "7045283494",
    "email": "Jitendrachauhan986.jc@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 34,
    "name": "Meghana",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "28th July",
    "interviewStart": "4:00 PM",
    "interviewEnd": "4:30 PM",
    "contact": "9480415383",
    "email": "meghananraj002@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 35,
    "name": "Premsai",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "27th July",
    "interviewStart": "4:00 PM",
    "interviewEnd": "4:30 PM",
    "contact": "99493 63733",
    "email": "indlapremsai5@gmail.com",
    "interview1": "L1",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 36,
    "name": "Ankit Goyal",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "24th July",
    "interviewStart": "4:00 PM",
    "interviewEnd": "4:30 PM",
    "contact": "8109537550",
    "email": "ankit931goyal@gmail.com",
    "interview1": "Candidate No Show",
    "interview2": "",
    "clientFeedback": "Drop",
    "presentCtcRaw": "",
    "status": "Candidate No Show",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 37,
    "name": "Sirisha GA",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "28th July",
    "interviewStart": "6:00 PM",
    "interviewEnd": "6:30 PM",
    "contact": "8904269587",
    "email": "sirishaanand2021@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 38,
    "name": "Ranjeeta Sinha",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "30th March",
    "interviewStart": "1:00 PM",
    "interviewEnd": "1:30 PM",
    "contact": "9930028693",
    "email": "ranssinha@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer shortlisted",
    "presentCtcRaw": "INR 10,00,000",
    "status": "Offered",
    "offeredCtcRaw": "1250000",
    "doj": "03-08-2026",
    "onboard": "Onboarded",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 39,
    "name": "Sita Ratnam Nunna",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "30th March",
    "interviewStart": "6:00 PM",
    "interviewEnd": "6:30 PM",
    "contact": "6362594314",
    "email": "sitaratnamnunna@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 40,
    "name": "Shubhangi Kale",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "2nd April",
    "interviewStart": "1:30 PM",
    "interviewEnd": "2:00 PM",
    "contact": "7875482809",
    "email": "shubhangikl@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer shortlisted",
    "presentCtcRaw": "INR 21,00,000",
    "status": "Offered",
    "offeredCtcRaw": "2280000",
    "doj": "03-08-2026",
    "onboard": "Onboarded",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 41,
    "name": "Arpit Chitransh",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "30th March",
    "interviewStart": "2:00 PM",
    "interviewEnd": "2:30 PM",
    "contact": "8123702415",
    "email": "chitransh.arpit@hotmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Candidate No Show",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 42,
    "name": "Sathish Kumar H",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "30th March",
    "interviewStart": "12:00 PM",
    "interviewEnd": "12:30 PM",
    "contact": "9952022068",
    "email": "hsathishkumar@yahoo.co.in",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 43,
    "name": "Dr. Kumar Mahesh",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "2nd April",
    "interviewStart": "12:00 PM",
    "interviewEnd": "12:30 PM",
    "contact": "99127 48408",
    "email": "drmangs@rediffmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "INR 31,00,000",
    "status": "Offered",
    "offeredCtcRaw": "2700000",
    "doj": "03-08-2026",
    "onboard": "Onboarded",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 44,
    "name": "Saurav Sinha",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "9th April",
    "interviewStart": "1:00 PM",
    "interviewEnd": "1:30 PM",
    "contact": "7979980779",
    "email": "saurav4u24.7@gmail.com",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 45,
    "name": "Katam Veera Nagendra",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "9th April",
    "interviewStart": "11:00 AM",
    "interviewEnd": "11:30 AM",
    "contact": "9900981130",
    "email": "veeranagendra.k@gmail.com",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 46,
    "name": "Agalya Rajendran",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "9th April",
    "interviewStart": "12:00 PM",
    "interviewEnd": "12:30 PM",
    "contact": "9739609543",
    "email": "agalyarajendran89@gmail.com",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 47,
    "name": "Chakali Gowtham Kumar",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "31st March",
    "interviewStart": "3:30 PM",
    "interviewEnd": "4:00 PM",
    "contact": "9491506056",
    "email": "gowthamglimpse@gmail.co",
    "interview1": "Completed",
    "interview2": "",
    "clientFeedback": "Rejected",
    "presentCtcRaw": "",
    "status": "Rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 48,
    "name": "Ansar Shaik",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9494999040",
    "email": "ansar6633@gmail.com",
    "interview1": "On Hold",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 49,
    "name": "Satish Halappanavar",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7702448984",
    "email": "satish.halappanavar@gmail.com",
    "interview1": "On Hold",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 50,
    "name": "Anusha B Bhaskar",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9611242467",
    "email": "anushabhaskar22@gmail.com",
    "interview1": "On Hold",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 51,
    "name": "Vinay Kumar",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9990897384",
    "email": "vinay.kumar975@gmail.com",
    "interview1": "On Hold",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 52,
    "name": "Akshay Sanjay Karne",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9822863589",
    "email": "akshaykarne2622@gmail.com",
    "interview1": "On Hold",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 53,
    "name": "Manikannan Kannusamy",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7845758099",
    "email": "kannan6264@ymail.com",
    "interview1": "On Hold",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 54,
    "name": "Vasuki Natarajan",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9840652373",
    "email": "vasukinataraj@gmail.com",
    "interview1": "On Hold",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 55,
    "name": "Saiki Volvoikar",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7020280675",
    "email": "saili637@gmail.com",
    "interview1": "On Hold",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 56,
    "name": "Rajashekar Hachadad",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9158064241/ 9742987334",
    "email": "rajashekar.hachadad@gmail.com",
    "interview1": "On Hold",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 57,
    "name": "Rohit Bhandarakavate",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7411820126",
    "email": "rohit07.b@live.com",
    "interview1": "On Hold",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 59,
    "name": "Avinash Belure",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7020107049",
    "email": "avinashbelure3@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 60,
    "name": "Parmeshwar Madke",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9657484689",
    "email": "p.a.madke@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 61,
    "name": "Usha",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "-9123520344, 7790400000",
    "email": "ushamicrostar007@gmail.com ushakomathi@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 62,
    "name": "Gayatri Gireesh",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9946669004",
    "email": "gayatrignair97@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 63,
    "name": "Chaitail Khandelwal",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "96735 21129",
    "email": "chaitalip1404@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 64,
    "name": "Dr Aayesha",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "8450918056",
    "email": "gadhia.aayesha@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 65,
    "name": "Minal Mangesh Jadhav",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9833705850",
    "email": "snehal0579@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 66,
    "name": "Pravin",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9994977806",
    "email": "pravin.saminathan611@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 67,
    "name": "Abhilash Varma",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7416780293",
    "email": "bpav2716@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "RAVE Programmer",
    "roleSelected": ""
  },
  {
    "sno": 68,
    "name": "Siddhesh Chalke",
    "function": "CDM",
    "role": "RAVE Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9920366265",
    "email": "siddhesh.chalke230@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "RAVE Programmer",
    "roleSelected": ""
  },
  {
    "sno": 69,
    "name": "Ansari Aishabanu",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9167305261",
    "email": "Ansari.aisha1995@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 70,
    "name": "Aakansha Murekar",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9623594399",
    "email": "aakanshamurekar17@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 71,
    "name": "HARSHADA KHANDGE",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9167336527",
    "email": "khandgeharshada3@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 72,
    "name": "Shahin Jawle",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9137164279",
    "email": "jawleshahin05@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 73,
    "name": "Nikita Awate",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9324998020",
    "email": "awateniki259@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 74,
    "name": "Avinash Urhekar",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9987151806",
    "email": "avinash.urhekar@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 75,
    "name": "Vijay Halde",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9689161578",
    "email": "haldevijay31@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 76,
    "name": "Greeshma Jadhav",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "6362535051",
    "email": "greeshmasjadhav23@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 77,
    "name": "Jenish Evana Nvss",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "8499996516",
    "email": "jenish.evana@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 78,
    "name": "Medara Akhil Babu",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7075713045",
    "email": "makhilbabu003@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 79,
    "name": "Shravani Somayajula",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7259109615",
    "email": "sravz1890@gmail.com —",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 80,
    "name": "Lavanya Krishna",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "8217090954",
    "email": "sheshashayanj21@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 81,
    "name": "Lavanya Gunda",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9676830916",
    "email": "gundalavanya65@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 82,
    "name": "Vijitha Kumar",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7395932879",
    "email": "vijithakumar125@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 83,
    "name": "Devyani Supe",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9970138004",
    "email": "devyanisupe@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 84,
    "name": "Anila Balan B",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "8089567698",
    "email": "anilabalan97appu@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 85,
    "name": "Diksha Khandale",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7218002190",
    "email": "dikshakhandale11@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 86,
    "name": "Prajesh Patil",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "8308409633",
    "email": "prajeshpatil1122@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 87,
    "name": "Naga Vamsi",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9676683922",
    "email": "nagavamsi800@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 88,
    "name": "Arunachaleswari Panneerselvam",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9361569207",
    "email": "mailtoaru178@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 89,
    "name": "Alka Devvanshi",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "8318086835",
    "email": "alkadevvanshi25@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 90,
    "name": "Prajakta Kashalikar",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9657016429",
    "email": "Kashalikar.prajakta@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 91,
    "name": "M Rangaswamy",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9392887549",
    "email": "rangamandla1@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 92,
    "name": "Sauradeep Mitra",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9875327300",
    "email": "sauradeep15@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 93,
    "name": "Jay Bhalerao",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9890882898",
    "email": "jay9890882898@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 94,
    "name": "Nupur Shimpi",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "8600187410",
    "email": "nupsshimpi@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 95,
    "name": "SHWETHA H",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9164482907",
    "email": "h.shwethasonu24@gmal.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 96,
    "name": "Heena Kausar",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7406207665",
    "email": "heenakausar9666@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 97,
    "name": "Jigyansha Sandha",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7978907529",
    "email": "jinusandha21@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 98,
    "name": "Meher Taj",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "8147591150",
    "email": "angelmeherhk@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 99,
    "name": "Swetha Somalaraju",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9000961075",
    "email": "swethaswetya02@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 100,
    "name": "Yashwanth D",
    "function": "CDM",
    "role": "External Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9066993731",
    "email": "yashwanthd2098@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 101,
    "name": "Pranjali Patil",
    "function": "CDM",
    "role": "External Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7208307874",
    "email": "patilpranjalir@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 102,
    "name": "Rishil Shah",
    "function": "CDM",
    "role": "External Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9426284286",
    "email": "rxrishilshah@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 103,
    "name": "Shweta Shinde",
    "function": "CDM",
    "role": "External Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "8975315703",
    "email": "shwetashindek22@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 104,
    "name": "Sushmita Malik",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7715921131",
    "email": "sushmitamalik11@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 105,
    "name": "Megha Shasrei",
    "function": "CDM",
    "role": "External Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9824555643",
    "email": "megha.shastri88@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 106,
    "name": "Nikesh kumar",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9555199411",
    "email": "nikesh.pharmacist@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 107,
    "name": "Shraddha Mandale",
    "function": "CDM",
    "role": "UAT Tester",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9665387793",
    "email": "imandaleshraddha22@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 108,
    "name": "Harini D",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "6300412821",
    "email": "Harinireddydandu8148@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 109,
    "name": "Sadaf Faizan",
    "function": "CDM",
    "role": "External Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7838564408",
    "email": "sadaf.faizan2026@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 110,
    "name": "karthik jain",
    "function": "CDM",
    "role": "Lab Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "7509580099",
    "email": "jkartik255@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 111,
    "name": "Hemanth jadhav",
    "function": "CDM",
    "role": "Data Reviewer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9921017061",
    "email": "hemant2407jadhav@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 112,
    "name": "Aditya Grada",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "8180826804",
    "email": "adityagarad010798@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 113,
    "name": "Harish",
    "function": "CDM",
    "role": "Vendor Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9014291199",
    "email": "Vinnakotaharish9@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 114,
    "name": "Yadavalli Santhosh Krishna Chaitanya",
    "function": "CDM",
    "role": "External Data Manager",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "9885322927",
    "email": "yadavalli.chaitanya@gmail.com",
    "interview1": "Wait to schedule",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 115,
    "name": "Rashimi K J",
    "function": "CDM",
    "role": "External Data Manager",
    "interviewDate": "07-08-2026",
    "interviewStart": "1:00 PM",
    "interviewEnd": "1:30 PM",
    "contact": "9845414944",
    "email": "rashmi77.guruprasad@gmail.com, rashmikj1812@gmail.com",
    "interview1": "L1",
    "interview2": "",
    "clientFeedback": "Waiting for feedback",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "CDM",
    "roleSelected": ""
  },
  {
    "sno": 116,
    "name": "Naresh Kumar",
    "function": "CDM",
    "role": "Report Programmer",
    "interviewDate": "04-08-2026",
    "interviewStart": "3:30 PM",
    "interviewEnd": "4:00 PM",
    "contact": "9951511113",
    "email": "nareshnandu121@gmail.com",
    "interview1": "L1",
    "interview2": "",
    "clientFeedback": "Waiting for feedback",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 117,
    "name": "Shai Lakshmi",
    "function": "CDM",
    "role": "Report Programmer",
    "interviewDate": "",
    "interviewStart": "",
    "interviewEnd": "",
    "contact": "8096765691",
    "email": "maddiralashailakshmitriveni@gmail.com",
    "interview1": "",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "rejected",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 118,
    "name": "Himanshu Kumar Singh V",
    "function": "CDM",
    "role": "Report Programmer",
    "interviewDate": "04-08-2026",
    "interviewStart": "12:00 PM",
    "interviewEnd": "12:30 PM",
    "contact": "799-628-0870",
    "email": "himanshukumarsinghv@gmail.com",
    "interview1": "Completed",
    "interview2": "Completed",
    "clientFeedback": "Offer Shortlisted",
    "presentCtcRaw": "",
    "status": "Offer Shortlisted",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 119,
    "name": "Shayeestha Sheik",
    "function": "CDM",
    "role": "Report Programmer",
    "interviewDate": "12-08-2026",
    "interviewStart": "2.00 pm",
    "interviewEnd": "",
    "contact": "9538418561",
    "email": "sheikshayeestha@gmail.com",
    "interview1": "L1",
    "interview2": "",
    "clientFeedback": "Scheduled",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 120,
    "name": "Sandeep Gonela",
    "function": "CDM",
    "role": "Report Programmer",
    "interviewDate": "11-08-2026",
    "interviewStart": "3.30 pm",
    "interviewEnd": "",
    "contact": "9133557363",
    "email": "gonelasandeep94@gmail.com",
    "interview1": "L1",
    "interview2": "",
    "clientFeedback": "Waiting for feedback",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 121,
    "name": "Pranaya Pandharinath",
    "function": "CDM",
    "role": "Report Programmer",
    "interviewDate": "11-08-2026",
    "interviewStart": "1.30 pm",
    "interviewEnd": "",
    "contact": "9890418653 / 8766788270",
    "email": "pranayaghangale12@gmail.com",
    "interview1": "L1",
    "interview2": "",
    "clientFeedback": "Waiting for feedback",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 122,
    "name": "Nourin Fakruddin Mullannava",
    "function": "CDM",
    "role": "Report Programmer",
    "interviewDate": "11-08-2026",
    "interviewStart": "2.30 pm",
    "interviewEnd": "",
    "contact": "8197171190",
    "email": "nourinmullannavar@gmail.com",
    "interview1": "L1",
    "interview2": "",
    "clientFeedback": "Waiting for feedback",
    "presentCtcRaw": "",
    "status": "Waiting for feedback",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  },
  {
    "sno": 123,
    "name": "Ameer Basha Valluri",
    "function": "CDM",
    "role": "Report Programmer",
    "interviewDate": "07-08-2026",
    "interviewStart": "3:30 PM",
    "interviewEnd": "4:00 PM",
    "contact": "767398402",
    "email": "ameershahida143@gmail.com",
    "interview1": "Drop",
    "interview2": "",
    "clientFeedback": "",
    "presentCtcRaw": "",
    "status": "Pipeline",
    "offeredCtcRaw": "",
    "doj": "",
    "onboard": "",
    "skillGroup": "Report Programmer",
    "roleSelected": ""
  }
];
